spring:
  application:
    name: service-registry

server:
  port: 8762

eureka:
  instance:
    # 1. ADD THIS LINE: Explicitly define the hostname
    hostname: service-registry
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      # This is the "default node URL"
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/